name: demo-svc

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          generate_release_notes: true
          token: ${{ secrets.GH_TOKEN }}
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish
        run: |
          mvn --batch-mode deploy -Darguments=-DskipTests
        env:
          MAVEN_USERNAME: hzerip
          MAVEN_PASSWORD: ${{ secrets.GH_TOKEN }}